all:
	gcc -o binary/03pe01 03pe01.c
	gcc -o binary/03pe02 03pe02.c
	gcc -o binary/03pe03 03pe03.c
	gcc -o binary/03pe04 03pe04.c
	gcc -o binary/03pe05 03pe05.c
	gcc -o binary/03pe06 03pe06.c
	gcc -o binary/03pe07 03pe07.c
	gcc -o binary/03pe08 03pe08.c
	gcc -o binary/03pe09 03pe09.c
	gcc -o binary/03pe10 03pe10.c
	gcc -o binary/03pe11 03pe11.c
	gcc -o binary/03pe12 03pe12.c
	gcc -o binary/03pe13 03pe13.c
	gcc -o binary/03pe14 03pe14.c
	gcc -o binary/03pe15 03pe15.c
	gcc -o binary/03pe16 03pe16.c
	gcc -o binary/03pe17 03pe17.c
	gcc -o binary/03pe18 03pe18.c
	gcc -o binary/03pe19 03pe19.c
	gcc -o binary/03pe20 03pe20.c

.PHONY : clean
clean:
