all:
	gcc -o binary/06pe01 06pe01.c
	gcc -o binary/06pe02 06pe02.c
	#gcc -o binary/06pe03 06pe03.c
	#gcc -o binary/06pe04 06pe04.c
	#gcc -o binary/06pe05 06pe05.c
	#gcc -o binary/06pe06 06pe06.c
	#gcc -o binary/06pe07 06pe07.c
	#gcc -o binary/06pe08 06pe08.c
	#gcc -o binary/06pe09 06pe09.c
	#gcc -o binary/06pe10 06pe10.c
	#gcc -o binary/06pe11 06pe11.c
	#gcc -o binary/06pe12 06pe12.c
	#gcc -o binary/06pe13 06pe13.c
	#gcc -o binary/06pe14 06pe14.c
	#gcc -o binary/06pe15 06pe15.c	
.PHONY : clean
clean:
