all:
	gcc -o binary/05pe01 05pe01.c
	gcc -o binary/05pe02 05pe02.c
	gcc -o binary/05pe03 05pe03.c
	gcc -o binary/05pe04 05pe04.c
	gcc -o binary/05pe05 05pe05.c
	gcc -o binary/05pe06 05pe06.c
	gcc -o binary/05pe07 05pe07.c
	gcc -o binary/05pe08 05pe08.c
	gcc -o binary/05pe09 05pe09.c
	#skipped due to being too boring! gcc -o binary/05pe10 05pe10.c
	gcc -o binary/05pe11 05pe11.c
	gcc -o binary/05pe12 05pe12.c
	
.PHONY : clean
clean:
