all:
	gcc -std=c89 -pedantic -Wall -Werror 08pe01.c -o binary/08pe01
	gcc -std=c89 -pedantic -Wall -Werror 08pe02.c -o binary/08pe02
	gcc -std=c89 -pedantic -Wall -Werror 08pe03.c -o binary/08pe03
.PHONY : clean
clean:
